# -*- coding: utf-8 -*-
"""Build assets/content/horoscope_{en,si,ta}.json from one source (KAN-32).

Generated rather than hand-maintained so the three languages cannot drift
apart. A reader who switches language mid-day must see a translation of the
same prediction, which only holds if every file carries exactly the same ids
against the same conditions.

Run from the repo root:  python tool/content/build_content.py
"""
import io
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import part1_general_career as p1  # noqa: E402
import part2_money_love as p2  # noqa: E402
import part3_health_advice as p3  # noqa: E402

ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
OUT = os.path.join(ROOT, "assets", "content")

# The category each id prefix belongs to. Kept here rather than repeated on
# every entry: 200-odd lines of "category" would be noise, and a prefix typo
# fails loudly below instead of silently mis-filing a line.
PREFIX_CATEGORY = {
    "gen-": "general",
    "car-": "career",
    "mon-": "money",
    "lov-": "love",
    "hea-": "health",
    "adv-": "advice",
}

LANGS = ("en", "si", "ta")


def category_of(fragment_id):
    for prefix, category in PREFIX_CATEGORY.items():
        if fragment_id.startswith(prefix):
            return category
    raise SystemExit("id %r has no known category prefix" % fragment_id)


def main():
    entries = list(p1.FRAGMENTS) + list(p2.FRAGMENTS) + list(p3.FRAGMENTS)

    seen = set()
    for entry in entries:
        if len(entry) != 6:
            raise SystemExit("entry %r does not have 6 fields" % (entry[0],))
        fid = entry[0]
        if fid in seen:
            raise SystemExit("duplicate id %r" % fid)
        seen.add(fid)

    os.makedirs(OUT, exist_ok=True)
    counts = {}

    for index, lang in enumerate(LANGS):
        fragments = []
        for fid, requires, excludes, en, si, ta in entries:
            text = (en, si, ta)[index]
            if not text or not text.strip():
                raise SystemExit("%s has no %s text" % (fid, lang))
            record = {
                "id": fid,
                "category": category_of(fid),
                "text": text.strip(),
            }
            if requires:
                record["requires"] = list(requires)
            if excludes:
                record["excludes"] = list(excludes)
            fragments.append(record)

        path = os.path.join(OUT, "horoscope_%s.json" % lang)
        io.open(path, "w", encoding="utf-8", newline="\n").write(
            json.dumps(
                {
                    "_comment": (
                        "Generated by tool/content/build_content.py (KAN-32). "
                        "Do not edit by hand - edit the parts under "
                        "tool/content/ and rebuild, or the three languages "
                        "will drift apart."
                    ),
                    "fragments": fragments,
                },
                ensure_ascii=False,
                indent=2,
            )
            + "\n"
        )

        by_category = {}
        for f in fragments:
            by_category.setdefault(f["category"], 0)
            by_category[f["category"]] += 1
        counts[lang] = by_category
        print("%s: %d fragments" % (lang, len(fragments)))

    for category in sorted(PREFIX_CATEGORY.values()):
        unconditional = sum(
            1
            for fid, requires, excludes, _, _, _ in entries
            if category_of(fid) == category and not requires and not excludes
        )
        total = counts["en"][category]
        print("  %-8s %2d total, %2d unconditional" % (
            category, total, unconditional))


if __name__ == "__main__":
    main()
