# -*- coding: utf-8 -*-
"""Horoscope copy: health, and the closing advice (KAN-32).

Health copy names no condition, predicts no illness and recommends no
treatment. Rest, water, walking and "see someone if it persists" are the whole
vocabulary. Anything more would be medical advice from an app that carries an
entertainment disclaimer, and would deserve to be rejected at review.
"""

FRAGMENTS = [
    # ----------------------------------------------------------- health, any day
    ("hea-01", [], [], "Health holds steady; water and a short walk will carry you further than anything else.",
     "සෞඛ්‍යය ස්ථාවරය; ජලය හා කෙටි ඇවිදීමක් අන් සියල්ලට වඩා ඔබට උපකාරී වේ.",
     "உடல்நலம் நிலையானது; தண்ணீரும் சிறு நடையும் மற்ற அனைத்தையும் விட உதவும்."),
    ("hea-02", [], [], "Nothing troubling, though eating at regular hours helps more than usual.",
     "කරදරයක් නැත; එහෙත් නියමිත වේලාවට ආහාර ගැනීම සුපුරුදුට වඩා උපකාරී වේ.",
     "கவலை ஏதுமில்லை; ஆனால் நேரத்திற்கு உணவு உண்பது வழக்கத்தை விட உதவும்."),
    ("hea-03", [], [], "Sleep is the thing your body is asking for, not more effort.",
     "ඔබේ සිරුර ඉල්ලන්නේ වැඩි වෙහෙසක් නොව නින්දයි.",
     "உங்கள் உடல் கேட்பது கூடுதல் உழைப்பல்ல, தூக்கமே."),
    ("hea-04", [], [], "Stand up and move once an hour today.",
     "අද පැයකට වරක් නැගිට ඇවිදින්න.",
     "இன்று ஒரு மணி நேரத்திற்கு ஒருமுறை எழுந்து நடங்கள்."),
    ("hea-05", [], [], "The eyes and the shoulders take the strain this week.",
     "මෙම සතියේ ඇස් හා උරහිස් වෙහෙසට පත්වේ.",
     "இந்த வாரம் கண்களும் தோள்களும் அயர்ச்சி அடையும்."),
    ("hea-06", [], [], "Eat earlier in the evening than you have been.",
     "සවස ආහාරය සුපුරුදුට වඩා කලින් ගන්න.",
     "மாலை உணவை வழக்கத்தை விட முன்னதாக உண்ணுங்கள்."),
    ("hea-07", [], [], "A short rest in the afternoon is worth an hour of the evening.",
     "දහවල් කෙටි විවේකයක් සවස පැයකට වටී.",
     "மதியம் ஒரு சிறு ஓய்வு மாலை ஒரு மணி நேரத்திற்கு ஈடானது."),
    ("hea-08", [], [], "Fresh air changes the day more than you expect.",
     "නැවුම් වාතය ඔබ සිතනවාට වඩා දිනය වෙනස් කරයි.",
     "சுத்தமான காற்று நீங்கள் நினைப்பதை விட நாளை மாற்றும்."),
    ("hea-09", [], [], "Do not skip the meal you always skip.",
     "සැමවිටම මඟහරින ආහාර වේල අද මඟ නොහරින්න.",
     "எப்போதும் தவிர்க்கும் உணவை இன்று தவிர்க்காதீர்கள்."),
    ("hea-10", [], [], "Something you have been meaning to get checked deserves an appointment.",
     "පරීක්ෂා කරගන්නට සිතාගෙන සිටි දෙයකට වේලාවක් වෙන් කරන්න.",
     "பரிசோதிக்க நினைத்திருந்த ஒன்றுக்கு நேரம் ஒதுக்குங்கள்."),
    ("hea-11", [], [], "Energy is better in the first half of the day; plan around that.",
     "දිනයේ පළමු භාගයේ ශක්තිය වැඩිය; ඒ අනුව සැලසුම් කරන්න.",
     "நாளின் முதல் பாதியில் சக்தி அதிகம்; அதற்கேற்பத் திட்டமிடுங்கள்."),
    ("hea-12", [], [], "Less screen after dark will show by morning.",
     "රාත්‍රියේ තිර භාවිතය අඩු කළොත් උදෑසන එය දැනේ.",
     "இரவில் திரை பயன்பாட்டைக் குறைத்தால் காலையில் தெரியும்."),
    ("hea-13", [], [], "Warmth helps today — a hot drink, a warm bath, an early bed.",
     "අද උණුසුම උපකාරී වේ — උණුසුම් පානයක්, උණු දිය නෑමක්, කලින් නින්දක්.",
     "இன்று வெதுவெதுப்பு உதவும் — சூடான பானம், வெந்நீர் குளியல், முன்னதாகத் தூக்கம்."),
    ("hea-14", [], [], "Stretch before the day starts rather than after it ends.",
     "දිනය අවසානයේ නොව ආරම්භයට පෙර සිරුර දිගු කරන්න.",
     "நாள் முடிந்த பின் அல்ல, தொடங்கும் முன் உடலை நீட்டுங்கள்."),
    ("hea-15", [], [], "Company is good for you today; do not spend it all alone.",
     "අද සමාගම ඔබට හොඳය; සම්පූර්ණයෙන් තනිව නොසිටින්න.",
     "இன்று கூட்டுறவு நல்லது; முழுவதும் தனியாக இருக்க வேண்டாம்."),
    ("hea-16", [], [], "Appetite is uneven; eat lightly and often rather than heavily and late.",
     "රුචිය අස්ථිරය; බර ආහාර ප්‍රමාද වේලාවට වඩා සැහැල්ලුව නිතර ගන්න.",
     "பசி சீரற்றது; கனமான உணவை தாமதமாக உண்பதை விட லேசாக அடிக்கடி உண்ணுங்கள்."),
    ("hea-17", [], [], "The body is fine; it is the pace that needs adjusting.",
     "සිරුර හොඳින්ය; සකස් කළ යුත්තේ වේගයයි.",
     "உடல் நன்றாக உள்ளது; சரிசெய்ய வேண்டியது வேகமே."),
    ("hea-18", [], [], "Walk somewhere green if you can manage it.",
     "හැකි නම් හරිත පරිසරයක ඇවිදින්න.",
     "முடிந்தால் பசுமையான இடத்தில் நடங்கள்."),
    ("hea-19", [], [], "Take the stairs, take the long way, take your time.",
     "පඩිපෙළ භාවිත කරන්න, දිගු මාවත තෝරන්න, ඉක්මන් නොවන්න.",
     "படிக்கட்டைப் பயன்படுத்துங்கள், நீண்ட வழியைத் தேர்வு செய்யுங்கள், அவசரப்படாதீர்கள்."),
    ("hea-20", [], [], "A small habit begun today is easier to keep than one begun in January.",
     "අද ආරම්භ කරන කුඩා පුරුද්දක් අලුත් අවුරුද්දේ අරඹනවාට වඩා පහසුවෙන් රැකේ.",
     "இன்று தொடங்கும் சிறு பழக்கம் புத்தாண்டில் தொடங்குவதை விட எளிதாகத் தொடரும்."),
    ("hea-21", [], [], "Drink water before coffee or tea today.",
     "අද කෝපි හෝ තේට පෙර ජලය පානය කරන්න.",
     "இன்று காபி அல்லது தேநீருக்கு முன் தண்ணீர் குடியுங்கள்."),
    ("hea-22", [], [], "Rest is not idleness; you have earned an hour of it.",
     "විවේකය අලසකම නොවේ; ඔබ පැයක් උපයාගෙන ඇත.",
     "ஓய்வு சோம்பல் அல்ல; ஒரு மணி நேரம் நீங்கள் சம்பாதித்துள்ளீர்கள்."),
    ("hea-23", [], [], "Keep the evening free of anything that needs deciding.",
     "සවස තීරණ ගැනීමට අවශ්‍ය දෙයින් තොරව තබන්න.",
     "மாலையை முடிவெடுக்க வேண்டிய விஷயங்களிலிருந்து விடுவியுங்கள்."),
    ("hea-24", [], [], "Your mood follows your sleep this week, not the other way round.",
     "මෙම සතියේ ඔබේ මනෝභාවය නින්ද අනුව යයි; අනෙක් අතට නොවේ.",
     "இந்த வாரம் உங்கள் மனநிலை தூக்கத்தைப் பின்தொடர்கிறது; மாறாக அல்ல."),
    ("hea-25", [], [], "Sit up straighter than you are sitting now.",
     "දැන් සිටිනවාට වඩා කෙළින් වාඩි වන්න.",
     "இப்போது இருப்பதை விட நேராக அமருங்கள்."),
    ("hea-26", [], [], "One less thing in the evening will do more than one more in the morning.",
     "උදෑසන එකක් එකතු කරනවාට වඩා සවස එකක් අඩු කිරීම ඵලදායීය.",
     "காலையில் ஒன்றைச் சேர்ப்பதை விட மாலையில் ஒன்றைக் குறைப்பது பயனளிக்கும்."),
    ("hea-27", [], [], "If it has persisted more than a week, have it looked at.",
     "සතියකට වඩා පවතී නම් එය පරීක්ෂා කරවා ගන්න.",
     "ஒரு வாரத்திற்கு மேல் தொடர்ந்தால் அதைப் பரிசோதித்துக் கொள்ளுங்கள்."),
    ("hea-28", [], [], "Movement, not medicine, is what today calls for.",
     "අද අවශ්‍ය බෙහෙත් නොව චලනයයි.",
     "இன்று தேவைப்படுவது மருந்தல்ல, அசைவே."),
    ("hea-29", [], [], "Say no to the late night; you will thank yourself.",
     "රාත්‍රී අවදිවීමට නොකියන්න; පසුව ඔබට එය අගය කරනු ඇත.",
     "இரவு விழிப்புக்கு மறுத்துவிடுங்கள்; பின்னர் நன்றி சொல்வீர்கள்."),
    ("hea-30", [], [], "Steady breathing does more for a hard hour than anything else available.",
     "අමාරු පැයකට තිබෙන අන් සියල්ලට වඩා සන්සුන් හුස්ම ගැනීම ඵලදායීය.",
     "கடினமான ஒரு மணி நேரத்திற்கு மற்ற அனைத்தையும் விட நிதானமான மூச்சு உதவும்."),

    # ------------------------------------------------------- health, conditional
    ("hea-moon-hard", ["moon.difficult"], [],
     "Rest is worth more than effort today; sleep early if the day allows it.",
     "අද වෙහෙසට වඩා විවේකය වටී; හැකි නම් කලින් නිදාගන්න.",
     "இன்று உழைப்பை விட ஓய்வு மதிப்புமிக்கது; முடிந்தால் முன்னதாகத் தூங்குங்கள்."),
    ("hea-sat-diff", ["saturn.difficult"], [],
     "Old aches may speak up. Move gently rather than not at all.",
     "පැරණි වේදනා නැවත දැනිය හැක; නොසෙල්වී සිටිනවාට වඩා මෘදුව චලනය වන්න.",
     "பழைய வலிகள் மீண்டும் தெரியலாம்; அசையாமல் இருப்பதை விட மென்மையாக நகருங்கள்."),
    ("hea-sade", ["saturn.sadeSati"], [],
     "Saturn's season asks for routine — the same hours, the same meals, the same walk.",
     "ශනිගේ මෙම කාලය චර්යාවක් ඉල්ලයි — එකම වේලාවන්, එකම ආහාර, එකම ඇවිදීම.",
     "சனியின் இக்காலம் ஒழுங்கைக் கேட்கிறது — அதே நேரம், அதே உணவு, அதே நடை."),
    ("hea-mars-diff", ["mars.difficult"], [],
     "Kuja is sharp today; take care with heat, blades and haste.",
     "අද කුජ තියුණුය; ගින්දර, තියුණු දේ හා ඉක්මන් වීම ගැන පරෙස්සම් වන්න.",
     "இன்று செவ்வாய் கூர்மையானது; நெருப்பு, கூரிய பொருட்கள், அவசரம் ஆகியவற்றில் கவனம்."),
    ("hea-bright", ["mood.bright"], [],
     "Energy is unusually good; spend some of it on your body rather than your inbox.",
     "ශක්තිය අසාමාන්‍ය ලෙස හොඳය; එයින් කොටසක් වැඩට නොව සිරුරට යොදන්න.",
     "சக்தி வழக்கத்திற்கு மாறாக நன்றாக உள்ளது; அதில் சிறிதை வேலைக்கல்ல, உடலுக்குச் செலவிடுங்கள்."),
    ("hea-hard", ["mood.hard"], [],
     "Ask less of yourself today than you normally would.",
     "අද සුපුරුදුට වඩා ඔබෙන්ම අඩුවෙන් බලාපොරොත්තු වන්න.",
     "இன்று வழக்கத்தை விட உங்களிடமிருந்து குறைவாக எதிர்பாருங்கள்."),

    # ----------------------------------------------------------- advice, any day
    ("adv-01", [], [], "Do the difficult thing before noon.",
     "අමාරු දෙය දහවලට පෙර කරන්න.",
     "கடினமான வேலையை மதியத்திற்கு முன் செய்யுங்கள்."),
    ("adv-02", [], [], "Say less than you are tempted to say.",
     "කියන්නට සිතෙනවාට වඩා අඩුවෙන් කියන්න.",
     "சொல்லத் தோன்றுவதை விடக் குறைவாகச் சொல்லுங்கள்."),
    ("adv-03", [], [], "Finish one thing completely rather than three things partly.",
     "තුනක් අඩක් කරනවාට වඩා එකක් සම්පූර්ණයෙන් අවසන් කරන්න.",
     "மூன்றைப் பாதியாகச் செய்வதை விட ஒன்றை முழுமையாக முடியுங்கள்."),
    ("adv-04", [], [], "Ask, rather than assume.",
     "අනුමාන කරනවාට වඩා අසන්න.",
     "ஊகிப்பதை விடக் கேளுங்கள்."),
    ("adv-05", [], [], "Put it in writing.",
     "එය ලිඛිතව තබන්න.",
     "அதை எழுத்தில் வையுங்கள்."),
    ("adv-06", [], [], "Start before you feel ready.",
     "සූදානම් යැයි දැනෙන්නට පෙර ආරම්භ කරන්න.",
     "தயார் என்று உணரும் முன் தொடங்குங்கள்."),
    ("adv-07", [], [], "Let the other person finish speaking.",
     "අනෙක් තැනැත්තාට කථාව අවසන් කිරීමට ඉඩ දෙන්න.",
     "மற்றவர் பேசி முடிக்க இடம் கொடுங்கள்."),
    ("adv-08", [], [], "Choose the option you can undo.",
     "නැවත හරවා ගත හැකි විකල්පය තෝරන්න.",
     "திரும்பப் பெற முடிந்த தேர்வையே எடுங்கள்."),
    ("adv-09", [], [], "Keep your word about the small thing.",
     "කුඩා දෙය ගැන දුන් වචනය රකින්න.",
     "சிறிய விஷயத்தில் கொடுத்த வாக்கைக் காப்பாற்றுங்கள்."),
    ("adv-10", [], [], "Do not answer that message tonight.",
     "එම පණිවිඩයට අද රාත්‍රියේ පිළිතුරු නොදෙන්න.",
     "அந்தச் செய்திக்கு இன்றிரவு பதில் அளிக்க வேண்டாம்."),
    ("adv-11", [], [], "Take the advice you would give a friend.",
     "මිතුරෙකුට දෙන උපදෙසම ඔබත් ගන්න.",
     "நண்பருக்குக் கூறும் ஆலோசனையை நீங்களும் பின்பற்றுங்கள்."),
    ("adv-12", [], [], "Leave earlier than you need to.",
     "අවශ්‍ය වේලාවට වඩා කලින් පිටත් වන්න.",
     "தேவையான நேரத்தை விட முன்னதாகக் கிளம்புங்கள்."),
    ("adv-13", [], [], "One honest sentence is enough.",
     "අවංක වාක්‍යයක් ප්‍රමාණවත්ය.",
     "நேர்மையான ஒரு வாக்கியம் போதும்."),
    ("adv-14", [], [], "Do it badly rather than not at all.",
     "කිසිසේත් නොකරනවාට වඩා දුර්වල ලෙස හෝ කරන්න.",
     "செய்யாமல் இருப்பதை விட மோசமாகவேனும் செய்யுங்கள்."),
    ("adv-15", [], [], "Check once more before you send it.",
     "යැවීමට පෙර තව වරක් පරීක්ෂා කරන්න.",
     "அனுப்பும் முன் இன்னொருமுறை சரிபாருங்கள்."),
    ("adv-16", [], [], "Give it a day before you decide.",
     "තීරණය කිරීමට පෙර දිනක් ගන්න.",
     "முடிவெடுக்கும் முன் ஒரு நாள் எடுத்துக்கொள்ளுங்கள்."),
    ("adv-17", [], [], "Thank someone specifically, not generally.",
     "සාමාන්‍ය ලෙස නොව නිශ්චිතව යමෙකුට ස්තූති කරන්න.",
     "பொதுவாக அல்ல, குறிப்பாக ஒருவருக்கு நன்றி சொல்லுங்கள்."),
    ("adv-18", [], [], "Tidy one surface and the rest follows.",
     "එක් තැනක් පිළිවෙළට තබන්න; ඉතිරිය අනුව යයි.",
     "ஒரு இடத்தை ஒழுங்குபடுத்துங்கள்; மீதி தொடரும்."),
    ("adv-19", [], [], "Do not explain yourself twice.",
     "දෙවරක් ඔබ ගැන පැහැදිලි නොකරන්න.",
     "இரண்டு முறை உங்களை விளக்க வேண்டாம்."),
    ("adv-20", [], [], "Take the meeting outside if you can.",
     "හැකි නම් හමුවීම එළිමහනේ පවත්වන්න.",
     "முடிந்தால் சந்திப்பை வெளியில் வைத்துக்கொள்ளுங்கள்."),
    ("adv-21", [], [], "Return the thing you borrowed.",
     "ණයට ගත් දෙය ආපසු දෙන්න.",
     "கடன் வாங்கியதைத் திருப்பிக் கொடுங்கள்."),
    ("adv-22", [], [], "Be specific about when, not just about what.",
     "කුමක්ද යන්න පමණක් නොව කවදාද යන්නත් නිශ්චිත කරන්න.",
     "என்ன என்பதை மட்டுமல்ல, எப்போது என்பதையும் தெளிவாகச் சொல்லுங்கள்."),
    ("adv-23", [], [], "Trust the second thought, not the first.",
     "පළමු සිතුවිල්ලට වඩා දෙවැන්න විශ්වාස කරන්න.",
     "முதல் எண்ணத்தை விட இரண்டாவதை நம்புங்கள்."),
    ("adv-24", [], [], "Keep the promise you made to yourself.",
     "ඔබට ඔබම දුන් පොරොන්දුව රකින්න.",
     "உங்களுக்கு நீங்களே அளித்த வாக்கைக் காப்பாற்றுங்கள்."),
    ("adv-25", [], [], "Do not decide this while angry.",
     "කෝපයෙන් සිටියදී මෙය තීරණය නොකරන්න.",
     "கோபமாக இருக்கும்போது இதை முடிவு செய்ய வேண்டாம்."),
    ("adv-26", [], [], "Show the work before it is perfect.",
     "පරිපූර්ණ වීමට පෙර වැඩය පෙන්වන්න.",
     "முழுமையாகும் முன் வேலையைக் காட்டுங்கள்."),
    ("adv-27", [], [], "Cancel one thing to protect the rest.",
     "ඉතිරිය රැක ගැනීමට එකක් අවලංගු කරන්න.",
     "மீதியைப் பாதுகாக்க ஒன்றை ரத்து செய்யுங்கள்."),
    ("adv-28", [], [], "Give the benefit of the doubt once more.",
     "තව වරක් සැකයේ ප්‍රතිලාභය දෙන්න.",
     "இன்னொருமுறை சந்தேகத்தின் பலனைக் கொடுங்கள்."),
    ("adv-29", [], [], "Write down the idea before it leaves.",
     "අදහස නැති වීමට පෙර ලියා ගන්න.",
     "எண்ணம் மறையும் முன் எழுதி வையுங்கள்."),
    ("adv-30", [], [], "Go to bed on time and let tomorrow have it.",
     "නියමිත වේලාවට නිදාගෙන එය හෙටට තබන්න.",
     "நேரத்தில் தூங்கி அதை நாளைக்கு விடுங்கள்."),

    # ------------------------------------------------------- advice, conditional
    ("adv-sade", ["saturn.sadeSati"], [],
     "Saturn asks for discipline rather than luck. Keep your promises small and keep them.",
     "ශනි වාසනාවට වඩා විනය ඉල්ලයි; පොරොන්දු කුඩාව තබා ඒවා රකින්න.",
     "சனி அதிர்ஷ்டத்தை விட ஒழுக்கத்தைக் கேட்கிறது; வாக்குறுதிகளைச் சிறியதாக வைத்துக் காப்பாற்றுங்கள்."),
    ("adv-bright", ["mood.bright"], [],
     "Begin the thing you have been circling.",
     "වටේ යමින් සිටි දෙය දැන් ආරම්භ කරන්න.",
     "சுற்றி வந்துகொண்டிருந்த அந்த விஷயத்தை இப்போது தொடங்குங்கள்."),
    ("adv-hard", ["mood.hard"], [],
     "Postpone what can be postponed, and be kind to yourself about the rest.",
     "කල් දැමිය හැකි දේ කල් දමා ඉතිරිය ගැන ඔබටම කරුණාවන්ත වන්න.",
     "தள்ளிப்போட முடிந்ததைத் தள்ளிப்போட்டு, மீதியில் உங்களிடம் கருணையாக இருங்கள்."),
    ("adv-jup-fav", ["jupiter.favourable"], [],
     "Guru is with you; ask the question you have been saving.",
     "ගුරු ඔබ සමඟය; තබාගෙන සිටි ප්‍රශ්නය අසන්න.",
     "குரு உங்களுடன் உள்ளார்; சேமித்து வைத்த கேள்வியைக் கேளுங்கள்."),
    ("adv-moon-fav", ["moon.favourable"], [],
     "Trust your judgement today; it is clearer than usual.",
     "අද ඔබේ තීරණය විශ්වාස කරන්න; එය සුපුරුදුට වඩා පැහැදිලිය.",
     "இன்று உங்கள் முடிவை நம்புங்கள்; அது வழக்கத்தை விடத் தெளிவானது."),
    ("adv-kantaka", ["saturn.kantaka"], [],
     "Protect your rest this season; everything else depends on it.",
     "මෙම කාලයේ ඔබේ විවේකය රැක ගන්න; අන් සියල්ල එය මතය.",
     "இக்காலத்தில் உங்கள் ஓய்வைப் பாதுகாத்துக்கொள்ளுங்கள்; மற்ற அனைத்தும் அதைச் சார்ந்தது."),
    ("adv-ashtama", ["saturn.ashtama"], [],
     "Simplify one thing rather than adding another.",
     "තවත් එකක් එකතු කරනවාට වඩා එකක් සරල කරන්න.",
     "இன்னொன்றைச் சேர்ப்பதை விட ஒன்றை எளிமையாக்குங்கள்."),
]
