# -*- coding: utf-8 -*-
"""Horoscope copy: money, and relationships (KAN-32).

Money copy stays deliberately general. Naming an amount, an instrument or a
timing would be financial advice, which this app is not licensed to give and
which Play would be right to object to. "Look at what is going out" is fine;
"sell now" is not.
"""

FRAGMENTS = [
    # ------------------------------------------------------------ money, any day
    ("mon-01", [], [], "Money matters stay quiet — a good day to look at what is going out rather than what is coming in.",
     "මුදල් කටයුතු සන්සුන්ය; එන දෙයට වඩා යන දෙය දෙස බැලීමට හොඳ දිනයකි.",
     "பணம் சார்ந்த விஷயங்கள் அமைதி; வருவதை விட செலவாவதைப் பார்க்க நல்ல நாள்."),
    ("mon-02", [], [], "Nothing pressing financially, though a small debt is worth settling.",
     "හදිසි මුදල් ගැටලුවක් නැත; එහෙත් කුඩා ණයක් පියවා ගැනීම වටී.",
     "அவசர பணச் சிக்கல் இல்லை; ஆனால் சிறு கடனைத் தீர்ப்பது நல்லது."),
    ("mon-03", [], [], "A cost you had forgotten about resurfaces; it is smaller than you fear.",
     "අමතක වූ වියදමක් නැවත මතුවේ; එය බියවනවාට වඩා කුඩාය.",
     "மறந்துபோன ஒரு செலவு மீண்டும் வரும்; அது பயப்படுவதை விடச் சிறியது."),
    ("mon-04", [], [], "Count before you commit, not after.",
     "පොරොන්දු වීමට පෙර ගණන් බලන්න, පසුව නොවේ.",
     "வாக்குறுதி அளிப்பதற்கு முன் கணக்கிடுங்கள், பின்னர் அல்ல."),
    ("mon-05", [], [], "Someone owes you something small; today is a reasonable day to mention it.",
     "යමෙක් ඔබට කුඩා මුදලක් ණයය; අද එය මතක් කිරීමට සුදුසුය.",
     "யாரோ உங்களுக்குச் சிறு தொகை கடன்பட்டுள்ளார்; இன்று அதை நினைவூட்டலாம்."),
    ("mon-06", [], [], "A household expense arrives earlier in the month than expected.",
     "ගෘහස්ථ වියදමක් මාසයේ බලාපොරොත්තු වූවාට වඩා කලින් එයි.",
     "வீட்டுச் செலவு எதிர்பார்த்ததை விட மாதத்தில் முன்னதாக வரும்."),
    ("mon-07", [], [], "Keep the receipt. You will want it.",
     "රිසිට්පත තබා ගන්න; එය අවශ්‍ය වේ.",
     "ரசீதை வைத்திருங்கள்; அது தேவைப்படும்."),
    ("mon-08", [], [], "Lending to family today costs more than the money.",
     "අද පවුලේ අයට ණය දීම මුදලට වඩා වැඩි වියදමක් වේ.",
     "இன்று குடும்பத்தினருக்குக் கடன் கொடுப்பது பணத்தை விட அதிகம் செலவாகும்."),
    ("mon-09", [], [], "Small savings made now matter more than they look.",
     "දැන් කරන කුඩා ඉතිරි කිරීම් පෙනෙනවාට වඩා වැදගත්ය.",
     "இப்போது செய்யும் சிறு சேமிப்பு தோன்றுவதை விட முக்கியம்."),
    ("mon-10", [], [], "Compare two prices before you settle on one.",
     "එකක් තෝරාගැනීමට පෙර මිල දෙකක් සසඳන්න.",
     "ஒன்றைத் தேர்வு செய்யும் முன் இரண்டு விலைகளை ஒப்பிடுங்கள்."),
    ("mon-11", [], [], "An expense shared is easier than an expense hidden.",
     "සඟවන වියදමකට වඩා බෙදාගන්නා වියදම පහසුය.",
     "மறைக்கும் செலவை விட பகிரப்படும் செலவு எளிதானது."),
    ("mon-12", [], [], "The cheaper option is the right one this time.",
     "මෙවර ලාභ විකල්පය නිවැරදිය.",
     "இம்முறை மலிவான தேர்வே சரியானது."),
    ("mon-13", [], [], "Money spent on repair beats money spent on replacement today.",
     "අද අලුත් එකක් ගැනීමට වඩා අලුත්වැඩියාවට වියදම් කිරීම හොඳය.",
     "இன்று புதிதாக வாங்குவதை விட பழுதுபார்ப்பதற்குச் செலவிடுவது நல்லது."),
    ("mon-14", [], [], "A promise about money is worth writing down, even between friends.",
     "මිතුරන් අතර වුවද මුදල් පිළිබඳ පොරොන්දුවක් ලියා තැබීම වටී.",
     "நண்பர்களுக்கு இடையேயானாலும் பணம் பற்றிய வாக்குறுதியை எழுதி வைப்பது நல்லது."),
    ("mon-15", [], [], "Check the figure someone else calculated for you.",
     "වෙනත් අයෙකු ඔබ වෙනුවෙන් ගණනය කළ අගය පරීක්ෂා කරන්න.",
     "வேறொருவர் உங்களுக்காகக் கணக்கிட்ட எண்ணைச் சரிபாருங்கள்."),
    ("mon-16", [], [], "This is a month for steadying rather than stretching.",
     "මෙය දිගු කිරීමට නොව ස්ථාවර කිරීමට මාසයකි.",
     "இது விரிவாக்கும் மாதம் அல்ல, நிலைப்படுத்தும் மாதம்."),
    ("mon-17", [], [], "A discount that requires haste is not a discount.",
     "ඉක්මන් වීම අවශ්‍ය වට්ටමක් සැබෑ වට්ටමක් නොවේ.",
     "அவசரம் தேவைப்படும் தள்ளுபடி உண்மையான தள்ளுபடி அல்ல."),
    ("mon-18", [], [], "Something you own is worth more than you assume.",
     "ඔබ සතු යමක් ඔබ සිතනවාට වඩා වටිනවා.",
     "உங்களிடம் உள்ள ஒன்று நீங்கள் நினைப்பதை விட மதிப்புள்ளது."),
    ("mon-19", [], [], "Pay the small bill before the large one; it clears the mind.",
     "විශාල බිලට පෙර කුඩා බිල ගෙවන්න; සිත සැහැල්ලු වේ.",
     "பெரிய கட்டணத்திற்கு முன் சிறியதைச் செலுத்துங்கள்; மனம் இலகுவாகும்."),
    ("mon-20", [], [], "Income holds steady; it is the outgoings that need attention.",
     "ආදායම ස්ථාවරය; අවධානය අවශ්‍ය වන්නේ වියදම්වලටය.",
     "வருமானம் நிலையானது; கவனம் தேவைப்படுவது செலவுகளுக்கே."),
    ("mon-21", [], [], "Do not decide about money while tired.",
     "විඩාපත්ව සිටියදී මුදල් ගැන තීරණ නොගන්න.",
     "சோர்வாக இருக்கும்போது பணம் பற்றி முடிவெடுக்க வேண்டாம்."),
    ("mon-22", [], [], "An old subscription or standing payment deserves a look.",
     "පැරණි දායකත්වයක් හෝ නිතිපතා ගෙවීමක් නැවත බැලීම වටී.",
     "பழைய சந்தா அல்லது தொடர் கட்டணத்தை ஒருமுறை பாருங்கள்."),
    ("mon-23", [], [], "Generosity today is better given in time than in cash.",
     "අද ත්‍යාගශීලීත්වය මුදලින් නොව කාලයෙන් දෙන්න.",
     "இன்று உதவியை பணத்தில் அல்ல, நேரத்தில் கொடுங்கள்."),
    ("mon-24", [], [], "The money question is really a question about priorities.",
     "මුදල් ප්‍රශ්නය ඇත්තටම ප්‍රමුඛතා පිළිබඳ ප්‍රශ්නයකි.",
     "பணப் பிரச்சினை உண்மையில் முன்னுரிமை பற்றிய கேள்வி."),
    ("mon-25", [], [], "Wait a day on the larger purchase. It will still be there.",
     "විශාල මිලදී ගැනීම දිනකින් කල් දමන්න; එය එතැනම ඇත.",
     "பெரிய கொள்முதலை ஒரு நாள் தள்ளிப்போடுங்கள்; அது அங்கேயே இருக்கும்."),
    ("mon-26", [], [], "A cost split three ways is easier than a favour owed.",
     "ණයට ගන්නා උදව්වකට වඩා තිදෙනෙකු අතර බෙදූ වියදම පහසුය.",
     "கடன் வாங்கும் உதவியை விட மூவரிடையே பகிரப்பட்ட செலவு எளிது."),
    ("mon-27", [], [], "Keep a little back from what you planned to spend.",
     "වියදම් කිරීමට සැලසුම් කළ දෙයින් ටිකක් ඉතිරි කර ගන්න.",
     "செலவழிக்கத் திட்டமிட்டதில் கொஞ்சம் மிச்சம் வையுங்கள்."),
    ("mon-28", [], [], "The paperwork side of money needs an hour this week.",
     "මෙම සතියේ මුදල් සම්බන්ධ ලේඛන සඳහා පැයක් වෙන් කරන්න.",
     "இந்த வாரம் பணம் தொடர்பான ஆவணங்களுக்கு ஒரு மணி நேரம் ஒதுக்குங்கள்."),
    ("mon-29", [], [], "What looks like a loss now settles even within the month.",
     "දැන් අලාභයක් ලෙස පෙනෙන දෙය මාසය තුළම සමතුලිත වේ.",
     "இப்போது நஷ்டம் போல் தோன்றுவது மாதத்திற்குள் சரியாகும்."),
    ("mon-30", [], [], "Ask the price before you accept the work.",
     "වැඩය බාර ගැනීමට පෙර මිල අසන්න.",
     "வேலையை ஏற்பதற்கு முன் விலையைக் கேளுங்கள்."),

    # -------------------------------------------------------- money, conditional
    ("mon-ven-fav", ["venus.favourable"], ["saturn.sadeSati"],
     "Shukra is kind to your finances today; a purchase you have delayed is reasonable now.",
     "අද ශුක්‍ර ඔබේ මුදල් තත්ත්වයට හිතකරය; කල් දැමූ මිලදී ගැනීමක් දැන් සාධාරණය.",
     "இன்று சுக்கிரன் உங்கள் நிதிக்குச் சாதகம்; தள்ளிப்போட்ட கொள்முதல் இப்போது நியாயமானது."),
    ("mon-hard", ["mood.hard"], [],
     "Keep spending small today and let the larger decision wait a few days.",
     "අද වියදම් අඩුවෙන් තබා විශාල තීරණය දින කිහිපයක් කල් දමන්න.",
     "இன்று செலவைக் குறைத்து, பெரிய முடிவை சில நாட்கள் தள்ளிப்போடுங்கள்."),
    ("mon-sade", ["saturn.sadeSati"], [],
     "Saturn's stretch is not the season for a new financial commitment.",
     "ශනිගේ මෙම කාලය නව මූල්‍ය බැඳීමකට සුදුසු නොවේ.",
     "சனியின் இக்காலம் புதிய நிதிக் கடமைக்கு ஏற்றதல்ல."),
    ("mon-jup-fav", ["jupiter.favourable"], [],
     "Guru supports the second house of savings; put something aside today.",
     "ගුරු ධන ස්ථානයට හිතකරය; අද යමක් ඉතිරි කරන්න.",
     "குரு தன ஸ்தானத்திற்குச் சாதகம்; இன்று ஏதாவது சேமியுங்கள்."),
    ("mon-bright", ["mood.bright"], [],
     "A good day for a conversation about money you have been putting off.",
     "කල් දැමූ මුදල් සම්බන්ධ කතාබහකට හොඳ දිනයකි.",
     "தள்ளிப்போட்ட பணம் பற்றிய உரையாடலுக்கு நல்ல நாள்."),
    ("mon-sat-diff", ["saturn.difficult"], [],
     "Delays around payments are likely; chase gently and early.",
     "ගෙවීම් ප්‍රමාද විය හැක; කලින් හා මෘදුව මතක් කරන්න.",
     "கட்டணங்களில் தாமதம் ஏற்படலாம்; முன்கூட்டியே மென்மையாக நினைவூட்டுங்கள்."),

    # ------------------------------------------------------------- love, any day
    ("lov-01", [], [], "An easy day with the people close to you, if you make the time for them.",
     "කාලය වෙන් කළහොත් ළඟින්ම සිටින අය සමඟ පහසු දිනයකි.",
     "நேரம் ஒதுக்கினால் நெருங்கியவர்களுடன் எளிதான நாள்."),
    ("lov-02", [], [], "Someone is waiting for you to speak first.",
     "යමෙක් ඔබ මුලින්ම කථා කරනතුරු බලා සිටී.",
     "யாரோ நீங்கள் முதலில் பேசுவதற்குக் காத்திருக்கிறார்கள்."),
    ("lov-03", [], [], "Listening will do more today than explaining.",
     "අද පැහැදිලි කිරීමට වඩා සවන් දීම ඵලදායීය.",
     "இன்று விளக்குவதை விட கேட்பது பயனளிக்கும்."),
    ("lov-04", [], [], "A small kindness is remembered longer than a large gesture.",
     "විශාල ක්‍රියාවකට වඩා කුඩා කරුණාවක් දිගු කලක් මතක තබා ගනී.",
     "பெரிய செயலை விட சிறு கருணை நீண்ட நாள் நினைவில் இருக்கும்."),
    ("lov-05", [], [], "Do not read too much into a short reply.",
     "කෙටි පිළිතුරකින් වැඩිය අදහස් ගන්න එපා.",
     "சுருக்கமான பதிலுக்கு அதிக அர்த்தம் கற்பிக்க வேண்டாம்."),
    ("lov-06", [], [], "Family plans shift; go with the change rather than against it.",
     "පවුලේ සැලසුම් වෙනස් වේ; විරුද්ධ නොවී ඒ සමඟ යන්න.",
     "குடும்பத் திட்டங்கள் மாறும்; எதிர்க்காமல் அதனுடன் செல்லுங்கள்."),
    ("lov-07", [], [], "An apology given today lands well.",
     "අද පිරිනමන සමාවක් හොඳින් පිළිගැනේ.",
     "இன்று கேட்கும் மன்னிப்பு நன்கு ஏற்கப்படும்."),
    ("lov-08", [], [], "Time together matters more than what you do with it.",
     "එකට ගත කරන කාලය, කරන දෙයට වඩා වැදගත්ය.",
     "ஒன்றாகச் செலவிடும் நேரம், செய்யும் செயலை விட முக்கியம்."),
    ("lov-09", [], [], "A misunderstanding clears itself if you leave it alone for a day.",
     "දිනකට අත් හැරියොත් වැරදි වැටහීමක් තනිවම විසඳේ.",
     "ஒரு நாள் விட்டுவிட்டால் தவறான புரிதல் தானாகவே தீரும்."),
    ("lov-10", [], [], "Be the one who asks how their day was.",
     "ඔවුන්ගේ දවස ගැන අසන්නා ඔබ වන්න.",
     "அவர்களின் நாள் எப்படி இருந்தது எனக் கேட்பவராக இருங்கள்."),
    ("lov-11", [], [], "An old friendship is due a message from you.",
     "පැරණි මිත්‍රත්වයකට ඔබෙන් පණිවිඩයක් හිමිය.",
     "பழைய நட்புக்கு உங்களிடமிருந்து ஒரு செய்தி வேண்டும்."),
    ("lov-12", [], [], "Say the plain thing rather than the clever thing.",
     "දක්ෂ දෙයට වඩා සරල දෙය කියන්න.",
     "சாதுர்யமானதை விட எளிமையானதைச் சொல்லுங்கள்."),
    ("lov-13", [], [], "Someone's mood today has nothing to do with you.",
     "අද යමෙකුගේ මනෝභාවය ඔබ නිසා නොවේ.",
     "இன்று ஒருவரின் மனநிலை உங்களால் அல்ல."),
    ("lov-14", [], [], "A shared meal settles more than a long discussion.",
     "දිගු සාකච්ඡාවකට වඩා එකට ගන්නා ආහාර වේලක් දේවල් සමනය කරයි.",
     "நீண்ட விவாதத்தை விட ஒன்றாக உண்ணும் உணவு விஷயங்களைத் தணிக்கும்."),
    ("lov-15", [], [], "Give the benefit of the doubt today; it will be returned.",
     "අද සැකයේ ප්‍රතිලාභය දෙන්න; එය ආපසු ලැබේ.",
     "இன்று சந்தேகத்தின் பலனை கொடுங்கள்; அது திரும்பக் கிடைக்கும்."),
    ("lov-16", [], [], "Plans with a group go better than plans with one person.",
     "එක් අයෙකු සමඟ වඩා කණ්ඩායමක් සමඟ සැලසුම් හොඳින් සිදුවේ.",
     "ஒருவருடன் இருப்பதை விட குழுவுடன் திட்டமிடுவது சிறப்பாக இருக்கும்."),
    ("lov-17", [], [], "What went unsaid last week can be said today.",
     "පසුගිය සතියේ නොකී දෙය අද කිව හැක.",
     "கடந்த வாரம் சொல்லாதது இன்று சொல்லலாம்."),
    ("lov-18", [], [], "Be early rather than impressive.",
     "විශිෂ්ට වීමට වඩා වේලාසන පැමිණෙන්න.",
     "சிறப்பாக இருப்பதை விட நேரத்தில் வாருங்கள்."),
    ("lov-19", [], [], "A relative brings news you had not expected.",
     "නෑදෑයෙකු බලාපොරොත්තු නොවූ පුවතක් ගෙන එයි.",
     "உறவினர் எதிர்பாராத செய்தியைக் கொண்டுவருவார்."),
    ("lov-20", [], [], "Do not settle an argument by winning it.",
     "ආරවුලක් ජය ගැනීමෙන් විසඳන්න එපා.",
     "வாதத்தை வென்று தீர்க்க வேண்டாம்."),
    ("lov-21", [], [], "The house feels calmer if one small thing is put right.",
     "කුඩා දෙයක් හරි ගැස්සුවොත් නිවස සන්සුන් වේ.",
     "ஒரு சிறு விஷயத்தைச் சரிசெய்தால் வீடு அமைதியாகும்."),
    ("lov-22", [], [], "Affection shown in front of others counts double today.",
     "අද අන් අය ඉදිරියේ දක්වන ආදරය දෙගුණයක් වටී.",
     "இன்று மற்றவர்கள் முன் காட்டும் அன்பு இரட்டிப்பு மதிப்புடையது."),
    ("lov-23", [], [], "You are being harder on yourself than anyone else is.",
     "අන් කිසිවෙකුට වඩා ඔබ ඔබටම දැඩි වී සිටී.",
     "மற்ற யாரையும் விட நீங்களே உங்களிடம் கடுமையாக இருக்கிறீர்கள்."),
    ("lov-24", [], [], "A quiet evening at home is the right choice tonight.",
     "අද රාත්‍රියේ නිවසේ නිශ්ශබ්ද සැඳෑවක් නිවැරදි තේරීමයි.",
     "இன்றிரவு வீட்டில் அமைதியான மாலையே சரியான தேர்வு."),
    ("lov-25", [], [], "Someone wants your advice, not your solution.",
     "යමෙකුට අවශ්‍ය ඔබේ විසඳුම නොව උපදෙසයි.",
     "ஒருவருக்கு உங்கள் தீர்வு அல்ல, ஆலோசனையே தேவை."),
    ("lov-26", [], [], "An introduction made today is worth keeping up.",
     "අද සිදුවන හඳුනාගැනීමක් තබා ගැනීම වටී.",
     "இன்று ஏற்படும் அறிமுகத்தைத் தொடர்வது நல்லது."),
    ("lov-27", [], [], "Patience with a younger relative pays off this week.",
     "බාල නෑදෑයෙකු සමඟ ඉවසීම මෙම සතියේ ඵල දෙයි.",
     "இளைய உறவினருடன் பொறுமை இந்த வாரம் பலனளிக்கும்."),
    ("lov-28", [], [], "Say thank you to the person who is always there.",
     "සැමවිටම ළඟ සිටින තැනැත්තාට ස්තූතිය පවසන්න.",
     "எப்போதும் உடனிருப்பவருக்கு நன்றி சொல்லுங்கள்."),
    ("lov-29", [], [], "Distance today is space, not distance.",
     "අද ඇති දුර ඈත්වීමක් නොව අවකාශයකි.",
     "இன்றைய தூரம் விலகல் அல்ல, இடைவெளியே."),
    ("lov-30", [], [], "Make the plan concrete; vagueness is what disappoints people.",
     "සැලසුම නිශ්චිත කරන්න; අපැහැදිලිකමයි අන් අය කලකිරවන්නේ.",
     "திட்டத்தைத் தெளிவாக்குங்கள்; தெளிவின்மையே மற்றவரை ஏமாற்றுகிறது."),

    # --------------------------------------------------------- love, conditional
    ("lov-ven-fav", ["venus.favourable"], [],
     "Venus is well placed, and warmth offered today is likely to be returned.",
     "ශුක්‍ර හිතකර ස්ථානයක සිටී; අද දක්වන සෙනෙහස ආපසු ලැබේ.",
     "சுக்கிரன் சாதகமான இடத்தில்; இன்று காட்டும் அன்பு திரும்பக் கிடைக்கும்."),
    ("lov-mars-diff", ["mars.difficult"], [],
     "Kuja is restless; a sharp word will travel further than you intend.",
     "කුජ නොසන්සුන්ය; තියුණු වචනයක් ඔබ සිතනවාට වඩා දුර යයි.",
     "செவ்வாய் அமைதியற்றது; கூரிய வார்த்தை நீங்கள் நினைப்பதை விடத் தூரம் செல்லும்."),
    ("lov-moon-hard", ["moon.difficult"], [],
     "Feelings run closer to the surface than usual; give them a day.",
     "සුපුරුදුට වඩා හැඟීම් මතුපිටින්ම ඇත; දිනක් ඉඩ දෙන්න.",
     "வழக்கத்தை விட உணர்வுகள் மேலோட்டமாக உள்ளன; ஒரு நாள் அவகாசம் கொடுங்கள்."),
    ("lov-jup-fav", ["jupiter.favourable"], [],
     "Guru favours the seventh; partnership matters go smoothly.",
     "ගුරු සත්වන ස්ථානයට හිතකරය; සහකාරිත්ව කටයුතු සුමටව සිදුවේ.",
     "குரு ஏழாம் இடத்திற்குச் சாதகம்; கூட்டு விவகாரங்கள் சுமூகமாக நடக்கும்."),
    ("lov-sade", ["saturn.sadeSati"], [],
     "Saturn asks for steadiness at home rather than change.",
     "ශනි නිවසේ වෙනසකට වඩා ස්ථාවරත්වය ඉල්ලයි.",
     "சனி வீட்டில் மாற்றத்தை விட நிலைத்தன்மையைக் கேட்கிறது."),
    ("lov-bright", ["mood.bright"], [],
     "A rare day to say the thing you have been rehearsing.",
     "පුහුණු වෙමින් සිටි දෙය කීමට දුර්ලභ දිනයකි.",
     "பயிற்சி செய்து வந்ததைச் சொல்ல அரிய நாள்."),
]
