# -*- coding: utf-8 -*-
"""Horoscope copy: the day, and work (KAN-32).

Each entry is (id, requires, excludes, en, si, ta). One source for all three
languages so the id sets cannot drift apart — a reader who switches language
mid-day must get a translation of the same prediction, not a different one.

House style: one or two clauses, present tense, no promises, no medical or
financial instruction, nothing fatalistic. The app carries an entertainment
disclaimer and the copy should never strain it.
"""

FRAGMENTS = [
    # ---------------------------------------------------------- general, any day
    ("gen-01", [], [], "An ordinary day, and there is something to be said for one of those.",
     "සාමාන්‍ය දිනයකි; එවැනි දිනවලද තමන්ගේ වටිනාකමක් ඇත.",
     "சாதாரண நாள்; அத்தகைய நாட்களுக்கும் ஒரு மதிப்பு உண்டு."),
    ("gen-02", [], [], "Nothing pulls hard in either direction, so the day is largely yours to shape.",
     "කිසිවක් එක් පැත්තකට තදින් අදින්නේ නැත; දිනය හැඩගස්වා ගැනීම ඔබ අතේය.",
     "எதுவும் ஒரு பக்கம் இழுக்கவில்லை; நாளை வடிவமைப்பது உங்கள் கையில்."),
    ("gen-03", [], [], "Small things attended to early will keep the afternoon clear.",
     "උදෑසනම කුඩා දේ අවසන් කළොත් සවස නිදහස්ව තබා ගත හැක.",
     "காலையிலேயே சிறிய வேலைகளை முடித்தால் மதியம் அமைதியாக இருக்கும்."),
    ("gen-04", [], [], "The pace picks up after midday rather than before it.",
     "දහවලට පසුව දිනයේ වේගය වැඩි වේ.",
     "மதியத்திற்குப் பிறகு நாளின் வேகம் அதிகரிக்கும்."),
    ("gen-05", [], [], "A conversation you have been avoiding turns out easier than expected.",
     "ඔබ මඟහරිමින් සිටි කතාබහක් සිතුවාට වඩා පහසු වේ.",
     "நீங்கள் தவிர்த்து வந்த ஒரு உரையாடல் நினைத்ததை விட எளிதாக அமையும்."),
    ("gen-06", [], [], "Plans made today hold better than plans made in a hurry yesterday.",
     "අද සකසන සැලසුම් ඊයේ ඉක්මනින් සැකසූ ඒවාට වඩා ස්ථිර වේ.",
     "இன்று உருவாக்கும் திட்டங்கள் நேற்று அவசரமாக செய்தவற்றை விட உறுதியானவை."),
    ("gen-07", [], [], "Someone older than you has something worth hearing today.",
     "ඔබට වඩා වැඩිමහල් අයෙකුගෙන් අද ඇසීමට වටිනා දෙයක් ලැබේ.",
     "உங்களை விட மூத்த ஒருவரிடம் இன்று கேட்கத் தகுந்த ஒன்று உள்ளது."),
    ("gen-08", [], [], "Travel close to home goes smoothly; longer journeys need more margin.",
     "ළඟ ගමන් සුමටව සිදුවේ; දුර ගමන් සඳහා වැඩි කාලයක් තබා ගන්න.",
     "அருகிலுள்ள பயணங்கள் சுமூகமாக இருக்கும்; தூரப் பயணங்களுக்கு கூடுதல் நேரம் தேவை."),
    ("gen-09", [], [], "The morning is better suited to decisions than the evening.",
     "තීරණ ගැනීමට සවසට වඩා උදෑසන සුදුසුය.",
     "முடிவெடுக்க மாலையை விட காலை பொருத்தமானது."),
    ("gen-10", [], [], "An old matter comes back around, but in a gentler form.",
     "පැරණි කරුණක් නැවත මතුවේ; එහෙත් මෘදු ස්වරූපයෙන්.",
     "பழைய விஷயம் மீண்டும் வரும், ஆனால் மென்மையான வடிவில்."),
    ("gen-11", [], [], "You will get more done alone this morning than in company.",
     "අද උදෑසන කණ්ඩායමකට වඩා තනිව වැඩ කිරීම ඵලදායීය.",
     "இன்று காலை கூட்டாக இருப்பதை விட தனியாக வேலை செய்வது பலனளிக்கும்."),
    ("gen-12", [], [], "News arrives later in the day than you would like, but it arrives.",
     "පණිවිඩය බලාපොරොත්තු වූවාට වඩා ප්‍රමාද වුවත් ලැබේ.",
     "செய்தி எதிர்பார்த்ததை விட தாமதமாக வந்தாலும் வந்து சேரும்."),
    ("gen-13", [], [], "A routine you have kept quietly is starting to show its worth.",
     "නිහඬව රැක ගත් පුරුද්දක් දැන් එහි ඵලය පෙන්වයි.",
     "அமைதியாகக் கடைப்பிடித்த பழக்கம் இப்போது பலனளிக்கத் தொடங்குகிறது."),
    ("gen-14", [], [], "Keep the day's list short; two things finished beat five started.",
     "දවසේ ලැයිස්තුව කෙටි කරන්න; ආරම්භ කළ පහකට වඩා අවසන් කළ දෙකක් හොඳය.",
     "இன்றைய பட்டியலைச் சுருக்குங்கள்; தொடங்கிய ஐந்தை விட முடித்த இரண்டு சிறந்தது."),
    ("gen-15", [], [], "Something you assumed was settled deserves one more look.",
     "විසඳී ඇතැයි සිතූ දෙයක් නැවත වරක් බැලීම වටී.",
     "தீர்ந்துவிட்டது என நினைத்த ஒன்றை மீண்டும் ஒருமுறை பார்ப்பது நல்லது."),
    ("gen-16", [], [], "The day rewards patience more than cleverness.",
     "අද දින දක්ෂතාවයට වඩා ඉවසීම ඵල දෙයි.",
     "இன்று சாதுர்யத்தை விட பொறுமை பலனளிக்கும்."),
    ("gen-17", [], [], "A neighbour or colleague asks a small favour; it costs you little.",
     "අසල්වැසියෙකු හෝ සගයෙකු කුඩා උදව්වක් ඉල්ලයි; එය ඔබට බරක් නොවේ.",
     "அண்டை வீட்டார் அல்லது சகா சிறு உதவி கேட்பார்; அது உங்களுக்குப் பாரமல்ல."),
    ("gen-18", [], [], "You are further along than you think; stop to notice it.",
     "ඔබ සිතනවාට වඩා ඉදිරියෙන් සිටී; එය දැකීමට මොහොතක් ගන්න.",
     "நீங்கள் நினைப்பதை விட முன்னேறியுள்ளீர்கள்; அதைக் கவனிக்க ஒரு கணம் எடுங்கள்."),
    ("gen-19", [], [], "Written words carry further than spoken ones today.",
     "අද කථා කරන වචනවලට වඩා ලියන වචන දුර යයි.",
     "இன்று பேசும் வார்த்தைகளை விட எழுதும் வார்த்தைகள் தூரம் செல்லும்."),
    ("gen-20", [], [], "An interruption early on turns out to be the useful part of the day.",
     "උදෑසන ඇතිවන බාධාවක් දවසේ ප්‍රයෝජනවත්ම කොටස බවට පත්වේ.",
     "காலையில் ஏற்படும் இடையூறு நாளின் பயனுள்ள பகுதியாக மாறும்."),
    ("gen-21", [], [], "Home matters take priority over outside ones, and rightly so.",
     "පිටත කටයුතුවලට වඩා ගෘහ කටයුතු ප්‍රමුඛ වේ; එය නිවැරදිය.",
     "வெளி விஷயங்களை விட வீட்டு விஷயங்கள் முன்னுரிமை பெறும்; அது சரியே."),
    ("gen-22", [], [], "The day is steady rather than eventful, which suits what you need.",
     "දිනය සිදුවීම්වලින් පිරි නොවුණත් ස්ථාවරය; එය ඔබට ගැලපේ.",
     "நாள் நிகழ்வுகள் நிறைந்ததல்ல, ஆனால் நிலையானது; அது உங்களுக்குப் பொருந்தும்."),
    ("gen-23", [], [], "Say yes to the smaller invitation rather than the larger one.",
     "විශාල ආරාධනයට වඩා කුඩා ආරාධනය පිළිගන්න.",
     "பெரிய அழைப்பை விட சிறிய அழைப்பை ஏற்றுக்கொள்ளுங்கள்."),
    ("gen-24", [], [], "What looks like a delay is buying you time you will use.",
     "ප්‍රමාදයක් ලෙස පෙනෙන දෙය ඔබට ප්‍රයෝජනවත් වන කාලයක් ලබා දෙයි.",
     "தாமதம் போல் தோன்றுவது உங்களுக்குப் பயன்படும் நேரத்தைத் தருகிறது."),
    ("gen-25", [], [], "Keep one hour of the day unplanned; something will want it.",
     "දවසේ පැයක් සැලසුමකින් තොරව තබන්න; යමක් එය ඉල්ලා සිටී.",
     "நாளில் ஒரு மணி நேரத்தைத் திட்டமிடாமல் வையுங்கள்; ஏதோ ஒன்று அதைக் கேட்கும்."),
    ("gen-26", [], [], "A decision made quietly today saves an argument later.",
     "අද නිහඬව ගන්නා තීරණයක් පසුව ඇතිවන ආරවුලක් වළක්වයි.",
     "இன்று அமைதியாக எடுக்கும் முடிவு பின்னர் ஒரு வாதத்தைத் தவிர்க்கும்."),
    ("gen-27", [], [], "The afternoon is better for people, the morning for paperwork.",
     "උදෑසන ලේඛන කටයුතුවලටත්, සවස මිනිසුන් හමුවීමටත් සුදුසුය.",
     "காலை ஆவண வேலைகளுக்கும், மதியம் மக்களைச் சந்திப்பதற்கும் ஏற்றது."),
    ("gen-28", [], [], "Something misplaced turns up where you already looked.",
     "නැති වූ දෙයක් ඔබ දැනටමත් සෙවූ තැනකින්ම හමුවේ.",
     "தொலைந்த பொருள் நீங்கள் ஏற்கனவே தேடிய இடத்திலேயே கிடைக்கும்."),
    ("gen-29", [], [], "You have been carrying a small worry longer than it deserves.",
     "කුඩා කරදරයක් එය සුදුසු කාලයට වඩා දිගු කලක් ඔබ දරාගෙන සිටී.",
     "ஒரு சிறு கவலையை அது தகுதியான காலத்தை விட நீண்ட நாட்கள் சுமந்து வருகிறீர்கள்."),
    ("gen-30", [], [], "Today favours finishing over beginning.",
     "අද දිනය ආරම්භ කිරීමට වඩා අවසන් කිරීමට හිතකරය.",
     "இன்று தொடங்குவதை விட முடிப்பது சாதகமானது."),

    # ------------------------------------------------------ general, conditional
    ("gen-moon-fav", ["moon.favourable"], [],
     "The Moon sits well for you, and the day moves with less friction than it has lately.",
     "චන්ද්‍රයා ඔබට හිතකර ස්ථානයක සිටින බැවින් දිනය පහසුවෙන් ගෙවේ.",
     "சந்திரன் உங்களுக்கு சாதகமாக இருப்பதால் நாள் எளிதாகக் கழியும்."),
    ("gen-moon-hard", ["moon.difficult"], [],
     "The Moon is awkwardly placed, so expect the day to ask for more patience than usual.",
     "චන්ද්‍රයා අහිතකර ස්ථානයක සිටී; සුපුරුදුට වඩා ඉවසීමක් අවශ්‍ය වේ.",
     "சந்திரன் சாதகமற்ற இடத்தில் உள்ளது; வழக்கத்தை விட அதிக பொறுமை தேவைப்படும்."),
    ("gen-bright", ["mood.bright"], [],
     "Several placements agree with you at once, which is not common — use the room they give you.",
     "ග්‍රහ කිහිපයක්ම එකවර ඔබට හිතකරය; එය දුර්ලභය, එම අවකාශය භාවිත කරන්න.",
     "பல கிரகங்கள் ஒரே நேரத்தில் சாதகமாக உள்ளன; அது அரிது, அந்த வாய்ப்பைப் பயன்படுத்துங்கள்."),
    ("gen-hard", ["mood.hard"], [],
     "This is a day to hold your ground rather than to start something new.",
     "අලුත් දෙයක් අරඹනවාට වඩා තිබෙන තැන රැක ගැනීමට සුදුසු දිනයකි.",
     "புதிதாக ஒன்றைத் தொடங்குவதை விட இருக்கும் நிலையைத் தக்கவைக்க ஏற்ற நாள்."),
    ("gen-sade", ["saturn.sadeSati"], [],
     "Saturn is still moving through the heavy stretch around your Moon; steadiness matters more than speed.",
     "ශනි ඔබේ චන්ද්‍රයා අවට බර කාලය තුළ ගමන් කරයි; වේගයට වඩා ස්ථාවරත්වය වැදගත්ය.",
     "சனி உங்கள் சந்திரனைச் சுற்றிய கடினமான பகுதியில் நகர்கிறது; வேகத்தை விட நிலைத்தன்மை முக்கியம்."),
    ("gen-jup-fav", ["jupiter.favourable"], [],
     "Guru is well placed, and doors that were stuck give a little.",
     "ගුරු හිතකර ස්ථානයක සිටී; වැසී තිබූ දොරවල් ටිකක් විවර වේ.",
     "குரு சாதகமான இடத்தில் உள்ளார்; அடைபட்டிருந்த வாய்ப்புகள் சற்று திறக்கும்."),
    ("gen-kantaka", ["saturn.kantaka"], [],
     "Saturn presses on the fourth from your sign; home and rest need protecting this season.",
     "ශනි සිව්වන ස්ථානයට බලපායි; මෙම කාලයේ නිවස හා විවේකය රැක ගත යුතුය.",
     "சனி நான்காம் இடத்தில் அழுத்துகிறது; இக்காலத்தில் வீடும் ஓய்வும் பாதுகாக்கப்பட வேண்டும்."),
    ("gen-ashtama", ["saturn.ashtama"], [],
     "Saturn in the eighth asks you to simplify rather than to push.",
     "අටවන ශනි බලකිරීමට වඩා සරල කිරීමට කියයි.",
     "எட்டாம் இடத்தில் சனி வலியுறுத்துவதை விட எளிமையாக்கச் சொல்கிறது."),

    # ----------------------------------------------------------- career, any day
    ("car-01", [], [], "Steady progress at work, with nothing demanding a decision from you.",
     "රැකියාවේ ස්ථාවර ප්‍රගතියක්; ක්ෂණික තීරණයක් අවශ්‍ය නොවේ.",
     "வேலையில் நிலையான முன்னேற்றம்; அவசர முடிவு எதுவும் தேவையில்லை."),
    ("car-02", [], [], "A colleague needs more from you than they say outright.",
     "සගයෙකුට ඔහු කියනවාට වඩා ඔබෙන් උදව්වක් අවශ්‍යය.",
     "ஒரு சகாவுக்கு அவர் சொல்வதை விட அதிக உதவி தேவை."),
    ("car-03", [], [], "Finish the task you keep moving to tomorrow's list.",
     "හෙට දක්වා කල් දමන කාර්යය අද අවසන් කරන්න.",
     "நாளைக்குத் தள்ளிவரும் வேலையை இன்று முடியுங்கள்."),
    ("car-04", [], [], "Your work is noticed today, even if nobody says so.",
     "කිසිවෙකු නොකීවත් අද ඔබේ වැඩ නිරීක්ෂණය වේ.",
     "யாரும் சொல்லாவிட்டாலும் இன்று உங்கள் வேலை கவனிக்கப்படுகிறது."),
    ("car-05", [], [], "Put the difficult email before the easy one.",
     "පහසු ලිපියට පෙර අමාරු ලිපිය යවන්න.",
     "எளிதான கடிதத்திற்கு முன் கடினமானதை அனுப்புங்கள்."),
    ("car-06", [], [], "A question asked now saves a week of rework later.",
     "දැන් අසන ප්‍රශ්නයක් පසුව සතියක වැඩක් ඉතිරි කරයි.",
     "இப்போது கேட்கும் ஒரு கேள்வி பின்னர் ஒரு வார வேலையை மிச்சப்படுத்தும்."),
    ("car-07", [], [], "Keep your commitments modest today; you will be asked for more.",
     "අද පොරොන්දු අඩුවෙන් දෙන්න; තවත් ඉල්ලීම් එනු ඇත.",
     "இன்று வாக்குறுதிகளைக் குறைவாகக் கொடுங்கள்; மேலும் கேட்கப்படும்."),
    ("car-08", [], [], "An older piece of work resurfaces and proves useful.",
     "පැරණි කාර්යයක් නැවත මතුවී ප්‍රයෝජනවත් වේ.",
     "பழைய வேலை ஒன்று மீண்டும் வந்து பயனுள்ளதாக அமையும்."),
    ("car-09", [], [], "Do the thinking part before lunch and the talking part after.",
     "සිතීමේ කොටස දහවලට පෙරත්, කථා කිරීමේ කොටස පසුවත් කරන්න.",
     "சிந்திக்கும் பகுதியை மதியத்திற்கு முன்பும், பேசும் பகுதியை பின்பும் செய்யுங்கள்."),
    ("car-10", [], [], "Someone junior to you has the right answer; let them give it.",
     "ඔබට වඩා අඩු පළපුරුද්දක් ඇති අයෙකු නිවැරදි පිළිතුර දනී; ඔවුනට ඉඩ දෙන්න.",
     "உங்களை விட குறைந்த அனுபவமுள்ள ஒருவரிடம் சரியான பதில் உள்ளது; அவருக்கு இடம் கொடுங்கள்."),
    ("car-11", [], [], "Paperwork moves more easily than people today.",
     "අද මිනිසුන්ට වඩා ලේඛන කටයුතු පහසුවෙන් ඉදිරියට යයි.",
     "இன்று மனிதர்களை விட ஆவண வேலைகள் எளிதாக நகரும்."),
    ("car-12", [], [], "Do not agree to a date you have not checked.",
     "පරීක්ෂා නොකළ දිනයකට එකඟ නොවන්න.",
     "சரிபார்க்காத தேதிக்கு ஒப்புக்கொள்ளாதீர்கள்."),
    ("car-13", [], [], "A short conversation clears something a long email could not.",
     "දිගු ලිපියකට නොහැකි වූ දෙයක් කෙටි කතාබහකින් විසඳේ.",
     "நீண்ட கடிதத்தால் முடியாததை ஒரு சிறு உரையாடல் தீர்க்கும்."),
    ("car-14", [], [], "Progress is real but slower than it looks from inside.",
     "ප්‍රගතිය සැබෑය; එහෙත් ඇතුළතින් පෙනෙනවාට වඩා සෙමින්.",
     "முன்னேற்றம் உண்மையானது; ஆனால் உள்ளிருந்து தெரிவதை விட மெதுவானது."),
    ("car-15", [], [], "Tidy the work before showing it; it will be judged on the surface.",
     "පෙන්වීමට පෙර වැඩ පිළිවෙළට තබන්න; මතුපිටින් විනිශ්චය කෙරේ.",
     "காட்டுவதற்கு முன் வேலையை ஒழுங்குபடுத்துங்கள்; மேற்பரப்பால் மதிப்பிடப்படும்."),
    ("car-16", [], [], "You are the right person for the task, if not the fastest.",
     "වේගවත්ම නොවුණත් මෙම කාර්යයට සුදුසුම තැනැත්තා ඔබය.",
     "வேகமானவர் இல்லாவிட்டாலும் இந்த வேலைக்குப் பொருத்தமானவர் நீங்களே."),
    ("car-17", [], [], "A meeting ends better than it begins; stay for the end of it.",
     "රැස්වීමක් ආරම්භයට වඩා අවසානයේ හොඳය; අවසානය දක්වා රැඳී සිටින්න.",
     "கூட்டம் தொடக்கத்தை விட முடிவில் சிறப்பாக இருக்கும்; இறுதிவரை இருங்கள்."),
    ("car-18", [], [], "Write down what was agreed before the day ends.",
     "දිනය අවසන් වීමට පෙර එකඟ වූ දේ ලියා තබන්න.",
     "நாள் முடிவதற்குள் ஒப்புக்கொண்டதை எழுதி வையுங்கள்."),
    ("car-19", [], [], "The person who disagrees with you is doing you a favour.",
     "ඔබට විරුද්ධ වන තැනැත්තා ඇත්තටම ඔබට උදව්වක් කරයි.",
     "உங்களுடன் மாறுபடுபவர் உண்மையில் உங்களுக்கு உதவுகிறார்."),
    ("car-20", [], [], "Leave the last hour free; something will need it.",
     "අවසන් පැය නිදහස්ව තබන්න; යමකට එය අවශ්‍ය වේ.",
     "கடைசி மணி நேரத்தை விடுவியுங்கள்; ஏதோ ஒன்றுக்கு அது தேவைப்படும்."),
    ("car-21", [], [], "Ask for the thing you have decided not to ask for.",
     "ඉල්ලන්නේ නැතැයි තීරණය කළ දෙය ඉල්ලන්න.",
     "கேட்க வேண்டாம் என முடிவு செய்த ஒன்றைக் கேளுங்கள்."),
    ("car-22", [], [], "Two people are waiting on you for something small.",
     "කුඩා දෙයක් සඳහා දෙදෙනෙකු ඔබ එනතුරු බලා සිටී.",
     "ஒரு சிறிய விஷயத்திற்காக இருவர் உங்களை எதிர்பார்த்திருக்கிறார்கள்."),
    ("car-23", [], [], "Skill is not the constraint today; time is.",
     "අද බාධාව හැකියාව නොව කාලයයි.",
     "இன்று தடை திறமையல்ல, நேரமே."),
    ("car-24", [], [], "Decline the extra task politely rather than doing it badly.",
     "අමතර කාර්යය දුර්වල ලෙස කරනවාට වඩා ආචාරශීලීව ප්‍රතික්ෂේප කරන්න.",
     "கூடுதல் வேலையை மோசமாகச் செய்வதை விட பணிவாக மறுப்பது நல்லது."),
    ("car-25", [], [], "Check the detail everyone assumes someone else checked.",
     "අනෙකා පරීක්ෂා කළා යැයි සැමට සිතෙන කරුණ ඔබ පරීක්ෂා කරන්න.",
     "மற்றவர் சரிபார்த்தார் என அனைவரும் நினைக்கும் விஷயத்தை நீங்கள் பாருங்கள்."),
    ("car-26", [], [], "Good day for learning something, poor day for proving something.",
     "යමක් ඉගෙන ගැනීමට හොඳ දිනයකි; යමක් ඔප්පු කිරීමට නොවේ.",
     "ஒன்றைக் கற்க நல்ல நாள்; ஒன்றை நிரூபிக்க அல்ல."),
    ("car-27", [], [], "Your instinct about the timing is right; your instinct about the person is not.",
     "කාලය ගැන ඔබේ හැඟීම නිවැරදිය; පුද්ගලයා ගැන එය නොවේ.",
     "நேரம் பற்றிய உங்கள் உள்ளுணர்வு சரி; நபர் பற்றியது அல்ல."),
    ("car-28", [], [], "Send the reminder. Nobody will think less of you for it.",
     "මතක් කිරීම යවන්න; ඒ නිසා කිසිවෙකු ඔබ ගැන අඩුවෙන් නොසිතයි.",
     "நினைவூட்டலை அனுப்புங்கள்; அதற்காக யாரும் உங்களைக் குறைவாக நினைக்க மாட்டார்கள்."),
    ("car-29", [], [], "The simplest version of the plan is the one that will survive.",
     "සැලසුමේ සරලම ස්වරූපය තමයි ඉතිරි වන්නේ.",
     "திட்டத்தின் எளிமையான வடிவமே நிலைத்திருக்கும்."),
    ("car-30", [], [], "Today is for tidying the ground, not for planting.",
     "අද වැපිරීමට නොව බිම සකස් කිරීමට දිනයකි.",
     "இன்று விதைப்பதற்கல்ல, நிலத்தைத் தயார் செய்வதற்கு."),

    # ------------------------------------------------------- career, conditional
    ("car-jup-fav", ["jupiter.favourable"], [],
     "Guru favours your work sector — a good day to ask for what you have earned.",
     "ගුරු ඔබේ රැකියා පක්ෂයට හිතකරය; උපයාගත් දෙය ඉල්ලීමට හොඳ දිනයකි.",
     "குரு உங்கள் வேலைக்குச் சாதகம்; சம்பாதித்ததைக் கேட்க நல்ல நாள்."),
    ("car-sat-fav", ["saturn.favourable"], [],
     "Saturn rewards the unglamorous work today; finish what is half done.",
     "අද ශනි නොපෙනෙන වැඩට ඵල දෙයි; අඩක් කළ දේ අවසන් කරන්න.",
     "இன்று சனி மறைமுக உழைப்புக்குப் பலன் தரும்; பாதி செய்ததை முடியுங்கள்."),
    ("car-sade", ["saturn.sadeSati"], [],
     "Avoid making a large commitment at work this week if it can reasonably wait.",
     "කල් දැමිය හැකි නම් මෙම සතියේ රැකියාවේ විශාල පොරොන්දුවක් නොදෙන්න.",
     "தள்ளிப்போட முடியுமானால் இந்த வாரம் வேலையில் பெரிய வாக்குறுதி வேண்டாம்."),
    ("car-merc-fav", ["mercury.favourable"], [],
     "Budha is helpful — negotiations and documents go your way.",
     "බුධ හිතකරය; සාකච්ඡා හා ලේඛන ඔබට හිතකර ලෙස සිදුවේ.",
     "புதன் சாதகம்; பேச்சுவார்த்தைகளும் ஆவணங்களும் சாதகமாக அமையும்."),
    ("car-mars-diff", ["mars.difficult"], [],
     "Kuja is restless; do not take on a fight at work today.",
     "කුජ නොසන්සුන්ය; අද රැකියාවේ ගැටුමකට නොයන්න.",
     "செவ்வாய் அமைதியற்றது; இன்று வேலையில் மோதலுக்குப் போக வேண்டாம்."),
    ("car-bright", ["mood.bright"], [],
     "A rare day to put your name to something.",
     "යමකට ඔබේ නම යෙදීමට දුර්ලභ දිනයකි.",
     "ஒன்றில் உங்கள் பெயரைப் பதிக்க அரிய நாள்."),
]
