import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:nakshatra/core/astro/models.dart';
import 'package:nakshatra/features/horoscope/domain/fragment.dart';
import 'package:nakshatra/features/horoscope/domain/horoscope_engine.dart';
import 'package:nakshatra/features/horoscope/domain/horoscope_signals.dart';

/// The bundled copy (KAN-32).
///
/// Read from disk rather than through the asset bundle, so a malformed file
/// fails here rather than at runtime on someone's phone. The files are
/// generated by tool/content/build_content.py, but generated is not the same
/// as correct — the generator can only guarantee structure, not that a tag
/// exists or that a pool is large enough to last a month.
void main() {
  const languages = ['en', 'si', 'ta'];

  final byLanguage = <String, List<Fragment>>{};

  setUpAll(() {
    for (final lang in languages) {
      final file = File('assets/content/horoscope_$lang.json');
      expect(file.existsSync(), isTrue, reason: 'missing $lang copy');

      final json = jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
      byLanguage[lang] = [
        for (final f in json['fragments'] as List)
          Fragment.fromJson(f as Map<String, dynamic>),
      ];
    }
  });

  group('every language file', () {
    test('parses and is not empty', () {
      for (final lang in languages) {
        expect(byLanguage[lang], isNotEmpty, reason: lang);
      }
    });

    test('has unique ids', () {
      for (final lang in languages) {
        final ids = byLanguage[lang]!.map((f) => f.id).toList();
        expect(ids.toSet().length, ids.length, reason: lang);
      }
    });

    test('has no blank or placeholder text', () {
      for (final lang in languages) {
        for (final f in byLanguage[lang]!) {
          expect(f.text.trim(), isNotEmpty, reason: '${f.id} in $lang');
          expect(f.text, isNot(contains('TODO')), reason: '${f.id} in $lang');
          // A copied-but-not-translated line is the failure mode of hand
          // maintenance; catching the obvious case is cheap.
          expect(
            f.text.trim().length,
            greaterThan(8),
            reason: '${f.id} in $lang',
          );
        }
      }
    });
  });

  group('the three languages line up', () {
    test('exactly the same ids', () {
      // A reader who switches language mid-day must get a translation of the
      // same prediction, not a different prediction.
      final en = byLanguage['en']!.map((f) => f.id).toSet();
      for (final lang in ['si', 'ta']) {
        final other = byLanguage[lang]!.map((f) => f.id).toSet();
        expect(other.difference(en), isEmpty, reason: '$lang has extra ids');
        expect(en.difference(other), isEmpty, reason: '$lang is missing ids');
      }
    });

    test('the same category and conditions for each id', () {
      // The condition set decides *when* a line appears. If it differed
      // between languages, two readers on the same day would get different
      // predictions from the same app.
      final en = {for (final f in byLanguage['en']!) f.id: f};
      for (final lang in ['si', 'ta']) {
        for (final f in byLanguage[lang]!) {
          final reference = en[f.id]!;
          expect(f.category, reference.category, reason: '${f.id} in $lang');
          expect(f.requires, reference.requires, reason: '${f.id} in $lang');
          expect(f.excludes, reference.excludes, reason: '${f.id} in $lang');
        }
      }
    });

    test('Sinhala and Tamil are not just the English copied over', () {
      // Latin-only text in the si or ta file means a line was never actually
      // translated. A handful of proper nouns would be fine, so this allows a
      // few rather than demanding perfection.
      final latinOnly = RegExp(r'^[\x00-\x7F]+$');
      for (final lang in ['si', 'ta']) {
        final untranslated = byLanguage[lang]!
            .where((f) => latinOnly.hasMatch(f.text))
            .map((f) => f.id)
            .toList();
        expect(
          untranslated,
          isEmpty,
          reason: '$lang lines still in English: $untranslated',
        );
      }
    });
  });

  group('the pools are big enough', () {
    test('every category has at least 30 unconditional lines', () {
      // The engine steps one place per day, so an unconditional pool of N
      // lasts N days before anything repeats. Thirty is what makes the
      // "no repeat within a month" promise true on an ordinary day.
      for (final c in HoroscopeCategory.values) {
        final always = byLanguage['en']!.where(
          (f) => f.category == c && f.requires.isEmpty && f.excludes.isEmpty,
        );
        expect(
          always.length,
          greaterThanOrEqualTo(30),
          reason: '${c.name} has only ${always.length} unconditional lines',
        );
      }
    });

    // Conditional lines are treated differently from unconditional ones on
    // purpose. If Saturn is sitting on your Moon it is sitting there tomorrow
    // too, and saying so on both days is honest rather than repetitive. What
    // must not repeat is the ordinary copy that carries most of the reading.
    bool unconditional(List<Fragment> all, String id) {
      final f = all.firstWhere((x) => x.id == id);
      return f.requires.isEmpty && f.excludes.isEmpty;
    }

    test('a one-line section stays varied across a month', () {
      // Not "never repeats". Three properties are wanted at once - the same
      // reading on every device, lines that suit the day, and no repetition -
      // and they cannot all hold. Determinism is the one already promised to
      // readers, so it wins: selection is a pure function of the date, with
      // no stored history, which means eligibility churn occasionally lands
      // two days on the same line. Twenty distinct lines out of thirty in a
      // month is the real behaviour; a regression that broke rotation would
      // collapse this to a handful.
      final all = byLanguage['en']!;

      for (final category in HoroscopeCategory.values) {
        if (category == HoroscopeCategory.general) continue;

        final seen = <String>[];
        for (var d = 1; d <= 31; d++) {
          seen.addAll(
            _reading(all, DateTime(2026, 3, d)).fragmentIds.where(
              (id) =>
                  _categoryOf(all, id) == category && unconditional(all, id),
            ),
          );
        }
        expect(
          seen.toSet().length,
          greaterThanOrEqualTo(18),
          reason: '${category.name} showed only ${seen.toSet().length} lines',
        );
      }
    });

    test('the general section spends most of its pool in a month', () {
      // Three lines a day, so thirty unconditional lines are spent in ten.
      // Growing this pool is the next content increment.
      final all = byLanguage['en']!;
      final seen = <String>{};
      for (var d = 1; d <= 31; d++) {
        seen.addAll(
          _reading(all, DateTime(2026, 3, d)).fragmentIds.where(
            (id) =>
                _categoryOf(all, id) == HoroscopeCategory.general &&
                unconditional(all, id),
          ),
        );
      }
      expect(seen.length, greaterThanOrEqualTo(25));
    });

    test('consecutive days rarely share an ordinary line', () {
      // About seven times a month one of the eight lines in a reading also
      // appeared yesterday. That is the floor for this design rather than a
      // defect to tune away.
      //
      // Three things are wanted at once: the same reading on every device,
      // lines that suit the day, and no repetition. Determinism is the one
      // already promised to readers, so selection is a pure function of the
      // date with no stored history. That means the eligible set shifts as
      // the Moon changes sign, and a shifting set occasionally lands two days
      // on the same line. Excluding yesterday helps but cannot be exact,
      // because yesterday's reading itself excluded the day before, and that
      // chain cannot be followed without unbounded recursion.
      //
      // Larger pools push this down; it is inversely proportional to pool
      // size. The bound is deliberately close to the measured value so that a
      // real regression in rotation moves it.
      final all = byLanguage['en']!;
      var collisions = 0;
      for (var d = 1; d < 31; d++) {
        final today = _reading(
          all,
          DateTime(2026, 3, d),
        ).fragmentIds.where((id) => unconditional(all, id)).toSet();
        final tomorrow = _reading(
          all,
          DateTime(2026, 3, d + 1),
        ).fragmentIds.where((id) => unconditional(all, id)).toSet();
        collisions += today.intersection(tomorrow).length;
      }
      expect(
        collisions,
        lessThanOrEqualTo(10),
        reason: '$collisions in a month',
      );
    });

    test('no two days in a month produce the same reading', () {
      final readings = <String>{};
      for (var d = 1; d <= 31; d++) {
        readings.add(
          _reading(byLanguage['en']!, DateTime(2026, 3, d)).fragmentIds.join(),
        );
      }
      expect(readings.length, 31);
    });
  });

  group('conditions', () {
    test('every tag asked for is one the engine can produce', () {
      // A typo like "saturn.sadesati" makes a line silently invisible
      // forever, with nothing to notice it by.
      final produced = <String>{};
      for (final rasi in Rasi.values) {
        for (final saturn in Rasi.values) {
          for (final moon in Rasi.values) {
            produced.addAll(
              HoroscopeSignals.from(
                rasi: rasi,
                date: DateTime(2026, 9, 7),
                transiting: {
                  Graha.sun: Rasi.mesha,
                  Graha.moon: moon,
                  Graha.mars: Rasi.vrishabha,
                  Graha.mercury: Rasi.mesha,
                  Graha.jupiter: Rasi.mithuna,
                  Graha.venus: Rasi.meena,
                  Graha.saturn: saturn,
                  Graha.rahu: Rasi.tula,
                  Graha.ketu: Rasi.mesha,
                },
              ).tags,
            );
          }
        }
      }

      for (final f in byLanguage['en']!) {
        for (final tag in {...f.requires, ...f.excludes}) {
          expect(produced, contains(tag), reason: '${f.id} requires "$tag"');
        }
      }
    });
  });

  group('a real reading', () {
    Horoscope readingFor(Rasi sign, String lang) => HoroscopeEngine.build(
      signals: HoroscopeSignals.from(
        rasi: sign,
        date: DateTime(2026, 9, 7),
        transiting: {
          Graha.sun: Rasi.simha,
          Graha.moon: Rasi.tula,
          Graha.mars: Rasi.kanya,
          Graha.mercury: Rasi.simha,
          Graha.jupiter: Rasi.karka,
          Graha.venus: Rasi.kanya,
          Graha.saturn: Rasi.meena,
          Graha.rahu: Rasi.kumbha,
          Graha.ketu: Rasi.simha,
        },
      ),
      fragments: byLanguage[lang]!,
    );

    test('every sign gets every section, in every language', () {
      for (final lang in languages) {
        for (final sign in Rasi.values) {
          final h = readingFor(sign, lang);
          expect(
            h.sections.length,
            HoroscopeCategory.values.length,
            reason: 'a section was empty for ${sign.en} in $lang',
          );
        }
      }
    });

    test('the three languages choose the same lines', () {
      // Same ids in, same ids out — the language changes the words, never the
      // prediction.
      for (final sign in Rasi.values) {
        final en = readingFor(sign, 'en').fragmentIds;
        expect(readingFor(sign, 'si').fragmentIds, en, reason: sign.en);
        expect(readingFor(sign, 'ta').fragmentIds, en, reason: sign.en);
      }
    });
  });
}

/// A reading for a fixed sign, with the sky moving day to day so conditions
/// come and go the way they really do.
///
/// Chained through yesterday exactly as the providers do, because excluding
/// yesterday's lines is part of how a reading is produced.
Horoscope _reading(List<Fragment> fragments, DateTime date) {
  HoroscopeSignals signalsOn(DateTime d) => HoroscopeSignals.from(
    rasi: Rasi.meena,
    date: d,
    transiting: {
      Graha.sun: Rasi.kumbha,
      Graha.moon: Rasi.values[d.day % 12],
      Graha.mars: Rasi.makara,
      Graha.mercury: Rasi.kumbha,
      Graha.jupiter: Rasi.mithuna,
      Graha.venus: Rasi.meena,
      Graha.saturn: Rasi.meena,
      Graha.rahu: Rasi.kumbha,
      Graha.ketu: Rasi.simha,
    },
  );

  final avoid = HoroscopeEngine.build(
    signals: signalsOn(date.subtract(const Duration(days: 1))),
    fragments: fragments,
  ).fragmentIds.toSet();

  return HoroscopeEngine.build(
    signals: signalsOn(date),
    fragments: fragments,
    avoid: avoid,
  );
}

HoroscopeCategory _categoryOf(List<Fragment> fragments, String id) =>
    fragments.firstWhere((f) => f.id == id).category;
